projects:
  Codegen Project:
    schemaPath: generated/schema.json
    includes:
      - generated/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        docsFilePath: generated/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 5
extensions:
  amplify:
    version: 3
